spring:
  application:
    name: ollama-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: postgres
    password: 1234
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: hf.co/MLP-KTLim/llama-3-Korean-Bllossom-8B-gguf-Q4_K_M:Q4_K_M
          temperature: 0.3
      embedding:
        options:
          model: hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:Q4_K_M
      init:
        pull-model-strategy: always
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000
        initialize-schema: true

logging:
  level:
    com.example.demo.*: debug
    org.springframework.*: info
